import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Download, Copy, FileText, Check } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface GigData {
  title: string;
  short_description: string;
  description: string;
  tags: string[];
  faqs: { question: string; answer: string }[];
  requirements: string[];
  pricing_basic: { name: string; price: number; delivery: number; description: string; features: string[] };
  pricing_standard: { name: string; price: number; delivery: number; description: string; features: string[] };
  pricing_premium: { name: string; price: number; delivery: number; description: string; features: string[] };
  marketplace: string;
  service_name: string;
}

interface GigExportProps {
  gig: GigData;
}

export const GigExport = ({ gig }: GigExportProps) => {
  const { toast } = useToast();
  const [copied, setCopied] = useState<string | null>(null);

  const generateFiverrExport = () => {
    return `═══════════════════════════════════════════════════════
FIVERR GIG EXPORT - Ready to Paste
═══════════════════════════════════════════════════════

📌 GIG TITLE (paste in Title field)
─────────────────────────────────────────────────────
${gig.title}

📝 SHORT DESCRIPTION (paste in "Describe your Gig" field)
─────────────────────────────────────────────────────
${gig.short_description}

📄 FULL DESCRIPTION (paste in Gig Description)
─────────────────────────────────────────────────────
${gig.description}

🏷️ SEARCH TAGS (add these one by one)
─────────────────────────────────────────────────────
${gig.tags?.map((tag, i) => `${i + 1}. ${tag}`).join('\n') || 'No tags generated'}

💰 PRICING PACKAGES
─────────────────────────────────────────────────────

BASIC PACKAGE
• Name: ${gig.pricing_basic?.name || 'Basic'}
• Price: $${gig.pricing_basic?.price || 5}
• Delivery: ${gig.pricing_basic?.delivery || 3} days
• Description: ${gig.pricing_basic?.description || ''}
• Features:
${gig.pricing_basic?.features?.map(f => `  ✓ ${f}`).join('\n') || '  (No features listed)'}

STANDARD PACKAGE
• Name: ${gig.pricing_standard?.name || 'Standard'}
• Price: $${gig.pricing_standard?.price || 15}
• Delivery: ${gig.pricing_standard?.delivery || 5} days
• Description: ${gig.pricing_standard?.description || ''}
• Features:
${gig.pricing_standard?.features?.map(f => `  ✓ ${f}`).join('\n') || '  (No features listed)'}

PREMIUM PACKAGE
• Name: ${gig.pricing_premium?.name || 'Premium'}
• Price: $${gig.pricing_premium?.price || 30}
• Delivery: ${gig.pricing_premium?.delivery || 7} days
• Description: ${gig.pricing_premium?.description || ''}
• Features:
${gig.pricing_premium?.features?.map(f => `  ✓ ${f}`).join('\n') || '  (No features listed)'}

❓ FREQUENTLY ASKED QUESTIONS
─────────────────────────────────────────────────────
${gig.faqs?.map((faq, i) => `Q${i + 1}: ${faq.question}\nA: ${faq.answer}`).join('\n\n') || 'No FAQs generated'}

📋 BUYER REQUIREMENTS
─────────────────────────────────────────────────────
${gig.requirements?.map((req, i) => `${i + 1}. ${req}`).join('\n') || 'No requirements specified'}

═══════════════════════════════════════════════════════
Generated by GigAlly - https://gigally.app
═══════════════════════════════════════════════════════`;
  };

  const generateUpworkExport = () => {
    return `═══════════════════════════════════════════════════════
UPWORK PROJECT CATALOG EXPORT - Ready to Paste
═══════════════════════════════════════════════════════

📌 PROJECT TITLE
─────────────────────────────────────────────────────
${gig.title}

📝 PROJECT SUMMARY (Brief Description)
─────────────────────────────────────────────────────
${gig.short_description}

📄 DETAILED PROJECT DESCRIPTION
─────────────────────────────────────────────────────
${gig.description}

🔍 SPECIALIZATIONS & SKILLS (add as tags)
─────────────────────────────────────────────────────
${gig.tags?.join(', ') || 'No skills listed'}

💼 PROJECT SCOPE OPTIONS
─────────────────────────────────────────────────────

SMALL PROJECT
• Starting at: $${gig.pricing_basic?.price || 5}
• Timeline: ${gig.pricing_basic?.delivery || 3} days
• Scope: ${gig.pricing_basic?.description || 'Basic scope'}
• Deliverables:
${gig.pricing_basic?.features?.map(f => `  • ${f}`).join('\n') || '  (No deliverables listed)'}

MEDIUM PROJECT
• Starting at: $${gig.pricing_standard?.price || 15}
• Timeline: ${gig.pricing_standard?.delivery || 5} days
• Scope: ${gig.pricing_standard?.description || 'Standard scope'}
• Deliverables:
${gig.pricing_standard?.features?.map(f => `  • ${f}`).join('\n') || '  (No deliverables listed)'}

LARGE PROJECT
• Starting at: $${gig.pricing_premium?.price || 30}
• Timeline: ${gig.pricing_premium?.delivery || 7} days
• Scope: ${gig.pricing_premium?.description || 'Comprehensive scope'}
• Deliverables:
${gig.pricing_premium?.features?.map(f => `  • ${f}`).join('\n') || '  (No deliverables listed)'}

❓ FAQ FOR YOUR PROFILE
─────────────────────────────────────────────────────
${gig.faqs?.map((faq, i) => `Q${i + 1}: ${faq.question}\nA: ${faq.answer}`).join('\n\n') || 'No FAQs generated'}

📋 WHAT I NEED FROM CLIENTS
─────────────────────────────────────────────────────
${gig.requirements?.map((req, i) => `${i + 1}. ${req}`).join('\n') || 'No requirements specified'}

═══════════════════════════════════════════════════════
Generated by GigAlly - https://gigally.app
═══════════════════════════════════════════════════════`;
  };

  const generateJSONExport = () => {
    return JSON.stringify({
      title: gig.title,
      shortDescription: gig.short_description,
      description: gig.description,
      tags: gig.tags,
      faqs: gig.faqs,
      requirements: gig.requirements,
      pricing: {
        basic: gig.pricing_basic,
        standard: gig.pricing_standard,
        premium: gig.pricing_premium
      },
      marketplace: gig.marketplace,
      serviceName: gig.service_name,
      exportedAt: new Date().toISOString(),
      exportedBy: "GigAlly"
    }, null, 2);
  };

  const copyToClipboard = async (content: string, type: string) => {
    await navigator.clipboard.writeText(content);
    setCopied(type);
    toast({
      title: "Copied!",
      description: `${type} content copied to clipboard`,
    });
    setTimeout(() => setCopied(null), 2000);
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type: type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Downloaded!",
      description: `${filename} has been downloaded`,
    });
  };

  const fiverrContent = generateFiverrExport();
  const upworkContent = generateUpworkExport();
  const jsonContent = generateJSONExport();

  return (
    <Card className="p-6">
      <div className="flex items-center gap-3 mb-6">
        <FileText className="h-6 w-6 text-primary" />
        <div>
          <h2 className="text-xl font-semibold">Export Gig Content</h2>
          <p className="text-sm text-muted-foreground">Download formatted files ready to paste into marketplaces</p>
        </div>
      </div>

      <Tabs defaultValue="fiverr">
        <TabsList className="grid w-full grid-cols-3 mb-6">
          <TabsTrigger value="fiverr">Fiverr Format</TabsTrigger>
          <TabsTrigger value="upwork">Upwork Format</TabsTrigger>
          <TabsTrigger value="json">JSON Data</TabsTrigger>
        </TabsList>

        <TabsContent value="fiverr" className="space-y-4">
          <div className="bg-muted/30 rounded-lg p-4 max-h-96 overflow-auto">
            <pre className="text-sm whitespace-pre-wrap font-mono">{fiverrContent}</pre>
          </div>
          <div className="flex gap-3">
            <Button 
              onClick={() => copyToClipboard(fiverrContent, "Fiverr")}
              variant="outline"
              className="flex-1"
            >
              {copied === "Fiverr" ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
              Copy to Clipboard
            </Button>
            <Button 
              onClick={() => downloadFile(fiverrContent, `${gig.service_name}-fiverr.txt`, "text/plain")}
              className="flex-1 bg-gradient-to-r from-primary to-secondary"
            >
              <Download className="mr-2 h-4 w-4" />
              Download .txt
            </Button>
          </div>
        </TabsContent>

        <TabsContent value="upwork" className="space-y-4">
          <div className="bg-muted/30 rounded-lg p-4 max-h-96 overflow-auto">
            <pre className="text-sm whitespace-pre-wrap font-mono">{upworkContent}</pre>
          </div>
          <div className="flex gap-3">
            <Button 
              onClick={() => copyToClipboard(upworkContent, "Upwork")}
              variant="outline"
              className="flex-1"
            >
              {copied === "Upwork" ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
              Copy to Clipboard
            </Button>
            <Button 
              onClick={() => downloadFile(upworkContent, `${gig.service_name}-upwork.txt`, "text/plain")}
              className="flex-1 bg-gradient-to-r from-primary to-secondary"
            >
              <Download className="mr-2 h-4 w-4" />
              Download .txt
            </Button>
          </div>
        </TabsContent>

        <TabsContent value="json" className="space-y-4">
          <div className="bg-muted/30 rounded-lg p-4 max-h-96 overflow-auto">
            <pre className="text-sm whitespace-pre-wrap font-mono">{jsonContent}</pre>
          </div>
          <div className="flex gap-3">
            <Button 
              onClick={() => copyToClipboard(jsonContent, "JSON")}
              variant="outline"
              className="flex-1"
            >
              {copied === "JSON" ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
              Copy to Clipboard
            </Button>
            <Button 
              onClick={() => downloadFile(jsonContent, `${gig.service_name}-data.json`, "application/json")}
              className="flex-1 bg-gradient-to-r from-primary to-secondary"
            >
              <Download className="mr-2 h-4 w-4" />
              Download .json
            </Button>
          </div>
        </TabsContent>
      </Tabs>
    </Card>
  );
};
